### PR TITLE
Add comment action as an update of PR-comment one

### LINKED ISSUE #11: Update `PR-comment` to allow commenting different owner/repo and to add a label for easily editing the same comment
Update the [pr-comment action](https://github.com/ACCESS-NRI/actions/blob/main/.github/actions/pr-comment/action.yml) to:

- include options for commenting a different owner/repo (providing the user has the right token permission)
- include a label as an input parameter, that would make it easier to edit/delete the same comment (comment with the same label)
- include a `delete` boolean option if a specific comment wants to be deleted.

### PR DESCRIPTION
**Pull request by atteggiani**
Fixes #11.

A new action called `comment` was added to update functionality of the [PR-comment](https://github.com/ACCESS-NRI/actions/blob/main/.github/actions/pr-comment/action.yml) action.

To better understand all the features, please read the [README](https://github.com/ACCESS-NRI/actions/blob/davide/pr-comment/.github/actions/comment/README.md).

### CODE REVIEW

**Comment by CodeGat** [comment]
Just before I get into reviewing this update to the action, I was wondering if it'd be better suited as a different action, since it breaks backwards compatibility. Just so it would be a more staggered approach to moving to the new action. Also, the action name (`pr-comment`) now seems to be more restrictive...Could we have a new action just named `comment`, maybe?

**Comment by atteggiani** [comment]
> Just before I get into reviewing this update to the action, I was wondering if it'd be better suited as a different action, since it breaks backwards compatibility. Just so it would be a more staggered approach to moving to the new action. Also, the action name (`pr-comment`) now seems to be more restrictive...Could we have a new action just named `comment`, maybe?

Yes it make sense. 
If you think it would be better to change name, then I would say we should set up a brand new action (I like the `comment` or `comment` name).
If naming is not a big issue, I would keep this one and back-compatibility could still be preserved by using the right ref (`uses: access-nri/actions/.github/actions/pr-comment@4134cbeec8523173798a1bfacccd79c967e58022` would be the current used one)

**Comment by CodeGat** [comment]
I think it might be best to have your action be a different name (`comment` does sound more general) and then slowly port over from `pr-comment` to `comment`. 
I know that we can use the commit ref, but if we are eventually moving all of them over to `comment` it would mean that we need to do two modifications to the various bits of infrastructure that do comments...so I think the `comment` action is best.

**Comment by atteggiani** [comment]
> I think it might be best to have your action be a different name (`comment` does sound more general) and then slowly port over from `pr-comment` to `comment`. I know that we can use the commit ref, but if we are eventually moving all of them over to `comment` it would mean that we need to do two modifications to the various bits of infrastructure that do comments...so I think the `comment` action is best.

Sure! 
I will move this to a new file called `comment.yml` then.

**Comment by atteggiani** [comment]
@CodeGat the suggested modifications have been applied. 
Instead of directly updating the existent `pr-comment` action, the new `comment` action was created.

**Review by CodeGat — APPROVED** [review]
Lovely, can't want to move over to this action!

**Pull request merged**
